// Code generated by gen.go. DO NOT EDIT.
// To avoid your changes from being overwritten, delete this header.

package products

import (
	"bnk.to/core/tools/services"

	pb "bnk.to/core/api/v1/products"
)

// DepositsServer is the implementation of DepositProductsService.
type DepositsServer struct {
	pb.UnsafeDepositProductsServiceServer
	services.Common
}

// LoansServer is the implementation of LoanProductsService.
type LoansServer struct {
	pb.UnsafeLoanProductsServiceServer
	services.Common
}

// RiskLevelsServer is the implementation of RiskLevelsService.
type RiskLevelsServer struct {
	pb.UnsafeRiskLevelsServiceServer
	services.Common
}

// NewDepositsServer creates a new DepositsServer.
func NewDepositsServer(common services.Common) *DepositsServer {
	return &DepositsServer{
		Common: common,
	}
}

// NewLoansServer creates a new LoansServer.
func NewLoansServer(common services.Common) *LoansServer {
	return &LoansServer{
		Common: common,
	}
}

// NewRiskLevelsServer creates a new RiskLevelsServer.
func NewRiskLevelsServer(common services.Common) *RiskLevelsServer {
	return &RiskLevelsServer{
		Common: common,
	}
}
