// Code generated by gen.go. DO NOT EDIT.
// To avoid your changes from being overwritten, delete this header.

package groups

import (
	"context"
	"time"

	pb "bnk.to/core/api/v1/groups"
	"bnk.to/core/tools/db"
	"bnk.to/core/tools/db/mux"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

func (s *Server) CreateGroup(ctx context.Context, req *pb.CreateGroupRequest) (*pb.Group, error) {
	if err := s.Auth.CheckPerm(ctx, req, "v1.groups.create"); err != nil {
		return nil, err
	}

	storage := mux.Storage(ctx)
	req.Body.CreateTime = timestamppb.New(time.Now())
	req.Body.UpdateTime = timestamppb.New(time.Now())
	v, err := db.NewGroup(req.Body)
	if err != nil {
		return nil, err
	}
	if err := storage.InsertGroup(ctx, &v); err != nil {
		return nil, err
	}
	return req.Body, nil
}
