// Code generated by gen.go. DO NOT EDIT.
// To avoid your changes from being overwritten, delete this header.

package groups

import (
	"context"

	pb "bnk.to/core/api/v1/groups"
	"bnk.to/core/tools/db"
	"bnk.to/core/tools/db/mux"
)

func (s *Server) CreateRole(ctx context.Context, req *pb.CreateRoleRequest) (*pb.Role, error) {
	if err := s.Auth.CheckPerm(ctx, req, "v1.groups.roles.create"); err != nil {
		return nil, err
	}

	storage := mux.Storage(ctx)
	v, err := db.NewGroupRole(req.Body)
	if err != nil {
		return nil, err
	}
	if err := storage.InsertGroupRole(ctx, &v); err != nil {
		return nil, err
	}
	return req.Body, nil
}
