// Code generated by gen.go. DO NOT EDIT.
// To avoid your changes from being overwritten, delete this header.

package currencies

import (
	"context"

	pb "bnk.to/core/api/v1/currencies"
	"bnk.to/core/tools/db"
	"bnk.to/core/tools/db/mux"
)

func (s *RatesServer) CreateExchangeRate(ctx context.Context, req *pb.CreateExchangeRateRequest) (*pb.ExchangeRate, error) {
	if err := s.Auth.CheckPerm(ctx, req, "v1.currencies.exchange_rate.create"); err != nil {
		return nil, err
	}

	storage := mux.Storage(ctx)
	v, err := db.NewCurrencyExchangeRate(req.Body)
	if err != nil {
		return nil, err
	}
	if err := storage.InsertCurrencyExchangeRate(ctx, &v); err != nil {
		return nil, err
	}
	return req.Body, nil
}
