// Code generated by gen.go. DO NOT EDIT.
// To avoid your changes from being overwritten, delete this header.

package currencies

import (
	"context"

	pb "bnk.to/core/api/v1/currencies"
	"bnk.to/core/tools/db/mux"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

func (s *Server) DeleteCurrency(ctx context.Context, req *pb.DeleteCurrencyRequest) (*emptypb.Empty, error) {
	if err := s.Auth.CheckPerm(ctx, req, "v1.currencies.delete"); err != nil {
		return nil, err
	}

	storage := mux.Storage(ctx)
	if err := storage.DeleteCurrencyByCode(ctx, req.Code); err != nil {
		return nil, err
	}
	return &emptypb.Empty{}, nil
}
