// Code generated by gen.go. DO NOT EDIT.
// To avoid your changes from being overwritten, delete this header.

package currencies

import (
	"context"

	pb "bnk.to/core/api/v1/currencies"
	"bnk.to/core/tools/db/mux"
)

func (s *Server) GetCurrency(ctx context.Context, req *pb.GetCurrencyRequest) (*pb.Currency, error) {
	if err := s.Auth.CheckPerm(ctx, req, "v1.currencies.get"); err != nil {
		return nil, err
	}

	storage := mux.Storage(ctx)
	v, err := storage.CurrencyByCode(ctx, req.Code)
	if err != nil {
		return nil, err
	}
	return v.PB()
}
