// Code generated by gen.go. DO NOT EDIT.
// To avoid your changes from being overwritten, delete this header.

package deposits

import (
	"bnk.to/core/tools/services"

	pb "bnk.to/core/api/v1/deposits"
)

// Server is the implementation of DepositsService.
type Server struct {
	pb.UnsafeDepositsServiceServer
	services.Common
}

// NewServer creates a new Server.
func NewServer(common services.Common) *Server {
	return &Server{
		Common: common,
	}
}
