// Code generated by gen.go. DO NOT EDIT.
// To avoid your changes from being overwritten, delete this header.

package backups

import (
	"context"
	"fmt"

	pb "bnk.to/core/api/v1/backups"

	corepb "bnk.to/core/api/v1"
)

func (s *Server) DownloadBackup(ctx context.Context, req *pb.DownloadBackupRequest) (*corepb.File, error) {
	if err := s.Auth.CheckPerm(ctx, req, "v1.backup.download"); err != nil {
		return nil, err
	}

	return nil, fmt.Errorf("unimplemented")
}
