# syntax=docker/dockerfile:1.3
FROM golang:1.18-alpine AS builder

WORKDIR /src

ENV VERSION=localdev

COPY go.mod go.sum .
RUN go mod download

COPY . .

WORKDIR cmd/openbank-core-gw
RUN --mount=type=cache,target=/root/.cache/go-build go build -ldflags="-w -s -X main.version=$VERSION" -o openbank-core-gw

FROM golang:1.18-alpine

WORKDIR /root
COPY --from=builder /src/cmd/openbank-core-gw/openbank-core-gw .

CMD ["sh", "-c", "./openbank-core-gw"]
