// Package postgres contains generated code from xo.
package postgres

// Code generated by xo. DO NOT EDIT.

import (
	"context"
	"fmt"

	"bnk.to/core/tools/db"
)

func (repo *Repository) InsertCardHoldConfig(ctx context.Context, chc *db.CardHoldConfig) error {
	const stmt = `INSERT INTO card_hold_configs
		(merchant_code, duration, description)
		VALUES ($1, $2, $3)
		RETURNING id`
	var id int
	row := repo.db.QueryRowContext(
		ctx, stmt,
		chc.MerchantCode, chc.Duration, chc.Description,
	)
	if err := row.Scan(&id); err != nil {
		return err
	}
	return nil
}

func (repo *Repository) ListCardHoldConfigs(ctx context.Context, filter string, pageSize int32, orderBy string, after *db.ListPosition) (db.ListStat, []*db.CardHoldConfig, *db.ListPosition, error) {
	if filter != "" {
		return db.ListStat{}, nil, nil, fmt.Errorf("filter is unimplemented")
	}
	if orderBy == "" {
		orderBy = "id"
	}
	whereClause := `
		(
			(all_entries.ordered_idx > $2) OR
			(all_entries.ordered_idx = $2 AND all_entries.id > $3)
		)
	`
	if after == nil {
		// Use placeholder values but always evaluate to true.
		whereClause = "$2::INTEGER = $3"
		after = &db.ListPosition{
			Data: 0,
			ID:   0,
		}
	}
	const stmt = `WITH all_entries AS (
			SELECT
				quote_ident($1) AS ordered_idx, card_hold_configs.id,

				card_hold_configs.merchant_code,
				card_hold_configs.duration,
				card_hold_configs.description
			FROM
				card_hold_configs
			WHERE
				%s
		), all_count AS (
			SELECT
				COUNT(*) AS count
			FROM
				all_entries
		), filtered AS (
			SELECT
				*
			FROM
				all_entries
			WHERE %s
		), filtered_count AS (
			SELECT
				COUNT(*) AS count
			FROM
				filtered
		)
		SELECT
			all_count.count, filtered_count.count,
			NULL, NULL,
			NULL, NULL, NULL
		FROM
			all_count
			CROSS JOIN filtered_count
		UNION ALL
		(
			SELECT
				*
			FROM
				all_count
				CROSS JOIN filtered_count
				CROSS JOIN filtered
			ORDER BY
				quote_ident($1), filtered.id
			LIMIT
				$4
		)`

	filterSQL := "TRUE" // TODO
	query := fmt.Sprintf(stmt, filterSQL, whereClause)
	rows, err := repo.db.QueryContext(ctx, query, "card_hold_configs."+orderBy, after.Data, after.ID, pageSize)
	if err != nil {
		return db.ListStat{}, nil, nil, err
	}

	defer rows.Close()
	result := make([]*db.CardHoldConfig, 0, pageSize)
	var nextPos db.ListPosition
	var listStat db.ListStat
	if !rows.Next() {
		return db.ListStat{}, nil, nil, rows.Err()
	}
	var x any
	if err := rows.Scan(
		&listStat.Total, &listStat.Remaining,
		&x, &x,
		&x, &x, &x,
	); err != nil {
		return db.ListStat{}, nil, nil, err
	}
	for rows.Next() {
		var next db.CardHoldConfig
		if err := rows.Scan(
			&listStat.Total, &listStat.Remaining,
			&nextPos.Data, &nextPos.ID,
			&next.MerchantCode, &next.Duration, &next.Description,
		); err != nil {
			return db.ListStat{}, nil, nil, err
		}
		result = append(result, &next)
	}
	if rows.Err() != nil {
		return db.ListStat{}, nil, nil, rows.Err()
	}
	return listStat, result, &nextPos, nil
}

func (repo *Repository) CardHoldConfigByID(ctx context.Context, id int32) (*db.CardHoldConfig, error) {
	const stmt = `SELECT
		card_hold_configs.id,

		card_hold_configs.merchant_code,
		card_hold_configs.duration,
		card_hold_configs.description
	FROM
		card_hold_configs
	WHERE
		id = $1`

	var chc db.CardHoldConfig
	row := repo.db.QueryRowContext(ctx, stmt, id)
	if err := row.Scan(
		&chc.ID,
		&chc.MerchantCode, &chc.Duration, &chc.Description,
	); err != nil {
		return nil, err
	}

	return &chc, nil
}

func (repo *Repository) UpdateCardHoldConfigByID(ctx context.Context, chc *db.CardHoldConfig) error {
	const stmt = `UPDATE card_hold_configs
	SET merchant_code=$1,
		duration=$2,
		description=$3
	WHERE id = $4`
	_, err := repo.db.ExecContext(
		ctx, stmt,
		chc.MerchantCode, chc.Duration, chc.Description, chc.ID,
	)
	return err
}

func (repo *Repository) DeleteCardHoldConfigByID(ctx context.Context, id int32) error {
	const stmt = `DELETE FROM card_hold_configs
	WHERE id = $1`
	_, err := repo.db.ExecContext(
		ctx, stmt,
		id,
	)
	return err
}

func (repo *Repository) CardHoldConfigByMerchantCode(ctx context.Context, merchantCode string) (*db.CardHoldConfig, error) {
	const stmt = `SELECT
		card_hold_configs.id,

		card_hold_configs.merchant_code,
		card_hold_configs.duration,
		card_hold_configs.description
	FROM
		card_hold_configs
	WHERE
		merchant_code = $1`

	var chc db.CardHoldConfig
	row := repo.db.QueryRowContext(ctx, stmt, merchantCode)
	if err := row.Scan(
		&chc.ID,
		&chc.MerchantCode, &chc.Duration, &chc.Description,
	); err != nil {
		return nil, err
	}

	return &chc, nil
}

func (repo *Repository) UpdateCardHoldConfigByMerchantCode(ctx context.Context, chc *db.CardHoldConfig) error {
	const stmt = `UPDATE card_hold_configs
	SET merchant_code=$1,
		duration=$2,
		description=$3
	WHERE merchant_code = $4`
	_, err := repo.db.ExecContext(
		ctx, stmt,
		chc.MerchantCode, chc.Duration, chc.Description, chc.MerchantCode,
	)
	return err
}

func (repo *Repository) DeleteCardHoldConfigByMerchantCode(ctx context.Context, merchantCode string) error {
	const stmt = `DELETE FROM card_hold_configs
	WHERE merchant_code = $1`
	_, err := repo.db.ExecContext(
		ctx, stmt,
		merchantCode,
	)
	return err
}
