// Package postgres contains generated code from xo.
package postgres

// Code generated by xo. DO NOT EDIT.

import (
	"context"
	"fmt"

	"bnk.to/core/tools/db"
)

func (repo *Repository) InsertContactInfo(ctx context.Context, ci *db.ContactInfo) error {
	const stmt = `INSERT INTO contact_infos
		(full_name, addresses, telephones, emails, language)
		VALUES ($1, $2, $3, $4, $5)
		RETURNING id`
	var id int
	row := repo.db.QueryRowContext(
		ctx, stmt,
		ci.FullName, ci.Addresses, ci.Telephones, ci.Emails, ci.Language,
	)
	if err := row.Scan(&id); err != nil {
		return err
	}
	return nil
}

func (repo *Repository) ListContactInfos(ctx context.Context, filter string, pageSize int32, orderBy string, after *db.ListPosition) (db.ListStat, []*db.ContactInfo, *db.ListPosition, error) {
	if filter != "" {
		return db.ListStat{}, nil, nil, fmt.Errorf("filter is unimplemented")
	}
	if orderBy == "" {
		orderBy = "id"
	}
	whereClause := `
		(
			(all_entries.ordered_idx > $2) OR
			(all_entries.ordered_idx = $2 AND all_entries.id > $3)
		)
	`
	if after == nil {
		// Use placeholder values but always evaluate to true.
		whereClause = "$2::INTEGER = $3"
		after = &db.ListPosition{
			Data: 0,
			ID:   0,
		}
	}
	const stmt = `WITH all_entries AS (
			SELECT
				quote_ident($1) AS ordered_idx, contact_infos.id,

				contact_infos.full_name,
				contact_infos.addresses,
				contact_infos.telephones,
				contact_infos.emails,
				contact_infos.language
			FROM
				contact_infos
			WHERE
				%s
		), all_count AS (
			SELECT
				COUNT(*) AS count
			FROM
				all_entries
		), filtered AS (
			SELECT
				*
			FROM
				all_entries
			WHERE %s
		), filtered_count AS (
			SELECT
				COUNT(*) AS count
			FROM
				filtered
		)
		SELECT
			all_count.count, filtered_count.count,
			NULL, NULL,
			NULL, NULL, NULL, NULL, NULL
		FROM
			all_count
			CROSS JOIN filtered_count
		UNION ALL
		(
			SELECT
				*
			FROM
				all_count
				CROSS JOIN filtered_count
				CROSS JOIN filtered
			ORDER BY
				quote_ident($1), filtered.id
			LIMIT
				$4
		)`

	filterSQL := "TRUE" // TODO
	query := fmt.Sprintf(stmt, filterSQL, whereClause)
	rows, err := repo.db.QueryContext(ctx, query, "contact_infos."+orderBy, after.Data, after.ID, pageSize)
	if err != nil {
		return db.ListStat{}, nil, nil, err
	}

	defer rows.Close()
	result := make([]*db.ContactInfo, 0, pageSize)
	var nextPos db.ListPosition
	var listStat db.ListStat
	if !rows.Next() {
		return db.ListStat{}, nil, nil, rows.Err()
	}
	var x any
	if err := rows.Scan(
		&listStat.Total, &listStat.Remaining,
		&x, &x,
		&x, &x, &x, &x, &x,
	); err != nil {
		return db.ListStat{}, nil, nil, err
	}
	for rows.Next() {
		var next db.ContactInfo
		if err := rows.Scan(
			&listStat.Total, &listStat.Remaining,
			&nextPos.Data, &nextPos.ID,
			&next.FullName, &next.Addresses, &next.Telephones, &next.Emails, &next.Language,
		); err != nil {
			return db.ListStat{}, nil, nil, err
		}
		result = append(result, &next)
	}
	if rows.Err() != nil {
		return db.ListStat{}, nil, nil, rows.Err()
	}
	return listStat, result, &nextPos, nil
}

func (repo *Repository) ContactInfoByID(ctx context.Context, id int32) (*db.ContactInfo, error) {
	const stmt = `SELECT
		contact_infos.id,

		contact_infos.full_name,
		contact_infos.addresses,
		contact_infos.telephones,
		contact_infos.emails,
		contact_infos.language
	FROM
		contact_infos
	WHERE
		id = $1`

	var ci db.ContactInfo
	row := repo.db.QueryRowContext(ctx, stmt, id)
	if err := row.Scan(
		&ci.ID,
		&ci.FullName, &ci.Addresses, &ci.Telephones, &ci.Emails, &ci.Language,
	); err != nil {
		return nil, err
	}

	return &ci, nil
}

func (repo *Repository) UpdateContactInfoByID(ctx context.Context, ci *db.ContactInfo) error {
	const stmt = `UPDATE contact_infos
	SET full_name=$1,
		addresses=$2,
		telephones=$3,
		emails=$4,
		language=$5
	WHERE id = $6`
	_, err := repo.db.ExecContext(
		ctx, stmt,
		ci.FullName, ci.Addresses, ci.Telephones, ci.Emails, ci.Language, ci.ID,
	)
	return err
}

func (repo *Repository) DeleteContactInfoByID(ctx context.Context, id int32) error {
	const stmt = `DELETE FROM contact_infos
	WHERE id = $1`
	_, err := repo.db.ExecContext(
		ctx, stmt,
		id,
	)
	return err
}
