// Package postgres contains generated code from xo.
package postgres

// Code generated by xo. DO NOT EDIT.

import (
	"context"
	"fmt"

	"bnk.to/core/tools/db"
)

func (repo *Repository) InsertOrgNonWorkingDay(ctx context.Context, onwd *db.OrgNonWorkingDay) error {
	const stmt = `INSERT INTO org_non_working_days
		(non_working_days)
		VALUES ($1)
		RETURNING id`
	var id int
	row := repo.db.QueryRowContext(
		ctx, stmt,
		onwd.NonWorkingDays,
	)
	if err := row.Scan(&id); err != nil {
		return err
	}
	return nil
}

func (repo *Repository) ListOrgNonWorkingDays(ctx context.Context, filter string, pageSize int32, orderBy string, after *db.ListPosition) (db.ListStat, []*db.OrgNonWorkingDay, *db.ListPosition, error) {
	if filter != "" {
		return db.ListStat{}, nil, nil, fmt.Errorf("filter is unimplemented")
	}
	if orderBy == "" {
		orderBy = "id"
	}
	whereClause := `
		(
			(all_entries.ordered_idx > $2) OR
			(all_entries.ordered_idx = $2 AND all_entries.id > $3)
		)
	`
	if after == nil {
		// Use placeholder values but always evaluate to true.
		whereClause = "$2::INTEGER = $3"
		after = &db.ListPosition{
			Data: 0,
			ID:   0,
		}
	}
	const stmt = `WITH all_entries AS (
			SELECT
				quote_ident($1) AS ordered_idx, org_non_working_days.id,

				org_non_working_days.non_working_days
			FROM
				org_non_working_days
			WHERE
				%s
		), all_count AS (
			SELECT
				COUNT(*) AS count
			FROM
				all_entries
		), filtered AS (
			SELECT
				*
			FROM
				all_entries
			WHERE %s
		), filtered_count AS (
			SELECT
				COUNT(*) AS count
			FROM
				filtered
		)
		SELECT
			all_count.count, filtered_count.count,
			NULL, NULL,
			NULL
		FROM
			all_count
			CROSS JOIN filtered_count
		UNION ALL
		(
			SELECT
				*
			FROM
				all_count
				CROSS JOIN filtered_count
				CROSS JOIN filtered
			ORDER BY
				quote_ident($1), filtered.id
			LIMIT
				$4
		)`

	filterSQL := "TRUE" // TODO
	query := fmt.Sprintf(stmt, filterSQL, whereClause)
	rows, err := repo.db.QueryContext(ctx, query, "org_non_working_days."+orderBy, after.Data, after.ID, pageSize)
	if err != nil {
		return db.ListStat{}, nil, nil, err
	}

	defer rows.Close()
	result := make([]*db.OrgNonWorkingDay, 0, pageSize)
	var nextPos db.ListPosition
	var listStat db.ListStat
	if !rows.Next() {
		return db.ListStat{}, nil, nil, rows.Err()
	}
	var x any
	if err := rows.Scan(
		&listStat.Total, &listStat.Remaining,
		&x, &x,
		&x,
	); err != nil {
		return db.ListStat{}, nil, nil, err
	}
	for rows.Next() {
		var next db.OrgNonWorkingDay
		if err := rows.Scan(
			&listStat.Total, &listStat.Remaining,
			&nextPos.Data, &nextPos.ID,
			&next.NonWorkingDays,
		); err != nil {
			return db.ListStat{}, nil, nil, err
		}
		result = append(result, &next)
	}
	if rows.Err() != nil {
		return db.ListStat{}, nil, nil, rows.Err()
	}
	return listStat, result, &nextPos, nil
}

func (repo *Repository) OrgNonWorkingDayByID(ctx context.Context, id int32) (*db.OrgNonWorkingDay, error) {
	const stmt = `SELECT
		org_non_working_days.id,

		org_non_working_days.non_working_days
	FROM
		org_non_working_days
	WHERE
		id = $1`

	var onwd db.OrgNonWorkingDay
	row := repo.db.QueryRowContext(ctx, stmt, id)
	if err := row.Scan(
		&onwd.ID,
		&onwd.NonWorkingDays,
	); err != nil {
		return nil, err
	}

	return &onwd, nil
}

func (repo *Repository) UpdateOrgNonWorkingDayByID(ctx context.Context, onwd *db.OrgNonWorkingDay) error {
	const stmt = `UPDATE org_non_working_days
	SET non_working_days=$1
	WHERE id = $2`
	_, err := repo.db.ExecContext(
		ctx, stmt,
		onwd.NonWorkingDays, onwd.ID,
	)
	return err
}

func (repo *Repository) DeleteOrgNonWorkingDayByID(ctx context.Context, id int32) error {
	const stmt = `DELETE FROM org_non_working_days
	WHERE id = $1`
	_, err := repo.db.ExecContext(
		ctx, stmt,
		id,
	)
	return err
}
