// Code generated by gen.go. DO NOT EDIT.
// To avoid your changes from being overwritten, delete this header.

package transactions

import (
	"context"

	pb "bnk.to/core/api/v1/transactions"
	"bnk.to/core/tools/db/mux"
)

func (s *DepositServer) GetDepositTransaction(ctx context.Context, req *pb.GetDepositTransactionRequest) (*pb.DepositTransaction, error) {
	if err := s.Auth.CheckPerm(ctx, req, "v1.deposits.transactions.get"); err != nil {
		return nil, err
	}

	storage := mux.Storage(ctx)
	v, err := storage.TransactionDepositTransactionByTransactionID(ctx, req.TransactionID)
	if err != nil {
		return nil, err
	}
	return v.PB()
}
