// Code generated by gen.go. DO NOT EDIT.
// To avoid your changes from being overwritten, delete this header.

package roles

import (
	"bnk.to/core/tools/services"

	pb "bnk.to/core/api/v1/roles"
)

// ClientsServer is the implementation of ClientRoleService.
type ClientsServer struct {
	pb.UnsafeClientRoleServiceServer
	services.Common
}

// UsersServer is the implementation of UserRolesService.
type UsersServer struct {
	pb.UnsafeUserRolesServiceServer
	services.Common
}

// NewClientsServer creates a new ClientsServer.
func NewClientsServer(common services.Common) *ClientsServer {
	return &ClientsServer{
		Common: common,
	}
}

// NewUsersServer creates a new UsersServer.
func NewUsersServer(common services.Common) *UsersServer {
	return &UsersServer{
		Common: common,
	}
}
