// Code generated by gen.go. DO NOT EDIT.
// To avoid your changes from being overwritten, delete this header.

package roles

import (
	"context"
	"time"

	pb "bnk.to/core/api/v1/roles"
	"bnk.to/core/tools/db"
	"bnk.to/core/tools/db/mux"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

func (s *UsersServer) UpdateUserRole(ctx context.Context, req *pb.UpdateUserRoleRequest) (*pb.UserRole, error) {
	if err := s.Auth.CheckPerm(ctx, req, "v1.roles.users.update"); err != nil {
		return nil, err
	}

	storage := mux.Storage(ctx)
	// Override UpdateTime to the current time.
	req.Body.UpdateTime = timestamppb.New(time.Now())
	v, err := db.NewRoleUserRole(req.Body)
	if err != nil {
		return nil, err
	}
	if err := storage.UpdateRoleUserRoleByRoleID(ctx, &v); err != nil {
		return nil, err
	}
	return req.Body, nil
}
