// Code generated by gen.go. DO NOT EDIT.
// To avoid your changes from being overwritten, delete this header.

package org

import (
	"context"
	"time"

	pb "bnk.to/core/api/v1/org"
	"bnk.to/core/tools/db"
	"bnk.to/core/tools/db/mux"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

func (s *HolidaysServer) CreateHoliday(ctx context.Context, req *pb.CreateHolidayRequest) (*pb.Holiday, error) {
	if err := s.Auth.CheckPerm(ctx, req, "v1.organization.holidays.general.create"); err != nil {
		return nil, err
	}

	storage := mux.Storage(ctx)
	req.Body.CreateTime = timestamppb.New(time.Now())
	v, err := db.NewOrgHoliday(req.Body)
	if err != nil {
		return nil, err
	}
	if err := storage.InsertOrgHoliday(ctx, &v); err != nil {
		return nil, err
	}
	return req.Body, nil
}
