// Code generated by gen.go. DO NOT EDIT.
// To avoid your changes from being overwritten, delete this header.

package org

import (
	"context"

	pb "bnk.to/core/api/v1/org"
	"bnk.to/core/tools/db"
	"bnk.to/core/tools/db/mux"
)

func (s *ChannelsServer) CreateChannel(ctx context.Context, req *pb.CreateChannelRequest) (*pb.Channel, error) {
	if err := s.Auth.CheckPerm(ctx, req, "v1.organization.channels.create"); err != nil {
		return nil, err
	}

	storage := mux.Storage(ctx)
	v, err := db.NewOrgChannel(req.Body)
	if err != nil {
		return nil, err
	}
	if err := storage.InsertOrgChannel(ctx, &v); err != nil {
		return nil, err
	}
	return req.Body, nil
}
