// Code generated by gen.go. DO NOT EDIT.
// To avoid your changes from being overwritten, delete this header.

package org

import (
	"context"

	pb "bnk.to/core/api/v1/org"
	"bnk.to/core/tools/db/mux"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

func (s *HolidaysServer) DeleteHoliday(ctx context.Context, req *pb.DeleteHolidayRequest) (*emptypb.Empty, error) {
	if err := s.Auth.CheckPerm(ctx, req, "v1.organization.holidays.general.delete"); err != nil {
		return nil, err
	}

	storage := mux.Storage(ctx)
	if err := storage.DeleteOrgHolidayByHolidayID(ctx, req.HolidayID); err != nil {
		return nil, err
	}
	return &emptypb.Empty{}, nil
}
