// Code generated by gen.go. DO NOT EDIT.
// To avoid your changes from being overwritten, delete this header.

package consumers

import (
	"context"

	pb "bnk.to/core/api/v1/consumers"
	"bnk.to/core/tools/db/mux"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

func (s *Server) DeleteConsumer(ctx context.Context, req *pb.DeleteConsumerRequest) (*emptypb.Empty, error) {
	if err := s.Auth.CheckPerm(ctx, req, "v1.consumers.delete"); err != nil {
		return nil, err
	}

	storage := mux.Storage(ctx)
	if err := storage.DeleteConsumerByConsumerID(ctx, req.ConsumerID); err != nil {
		return nil, err
	}
	return &emptypb.Empty{}, nil
}
