// Code generated by gen.go. DO NOT EDIT.
// To avoid your changes from being overwritten, delete this header.

package cards

import (
	"context"

	pb "bnk.to/core/api/v1/cards"
	"bnk.to/core/tools/db"
	"bnk.to/core/tools/db/mux"
)

func (s *HoldConfigServer) CreateHoldConfig(ctx context.Context, req *pb.CreateHoldConfigRequest) (*pb.HoldConfig, error) {
	if err := s.Auth.CheckPerm(ctx, req, "v1.holds.create"); err != nil {
		return nil, err
	}

	storage := mux.Storage(ctx)
	v, err := db.NewCardHoldConfig(req.Body)
	if err != nil {
		return nil, err
	}
	if err := storage.InsertCardHoldConfig(ctx, &v); err != nil {
		return nil, err
	}
	return req.Body, nil
}
