// Code generated by gen.go. DO NOT EDIT.
// To avoid your changes from being overwritten, delete this header.

package rates

import (
	"context"

	pb "bnk.to/core/api/v1/rates"
	"bnk.to/core/tools/db"
	"bnk.to/core/tools/db/mux"
)

func (s *Server) CreateSource(ctx context.Context, req *pb.CreateSourceRequest) (*pb.Source, error) {
	if err := s.Auth.CheckPerm(ctx, req, "v1.sources.create"); err != nil {
		return nil, err
	}

	storage := mux.Storage(ctx)
	v, err := db.NewRateSource(req.Body)
	if err != nil {
		return nil, err
	}
	if err := storage.InsertRateSource(ctx, &v); err != nil {
		return nil, err
	}
	return req.Body, nil
}
