// Code generated by gen.go. DO NOT EDIT.
// To avoid your changes from being overwritten, delete this header.

package loans

import (
	"context"

	pb "bnk.to/core/api/v1/loans"
	"bnk.to/core/tools/db/mux"
)

func (s *Server) GetInstallment(ctx context.Context, req *pb.GetInstallmentRequest) (*pb.Installment, error) {
	if err := s.Auth.CheckPerm(ctx, req, "v1.accounts.loans.installments.get"); err != nil {
		return nil, err
	}

	storage := mux.Storage(ctx)
	v, err := storage.LoanInstallmentByInstallmentID(ctx, req.InstallmentID)
	if err != nil {
		return nil, err
	}
	return v.PB()
}
