// Code generated by gen.go. DO NOT EDIT.
// To avoid your changes from being overwritten, delete this header.

package loans

import (
	"context"
	"fmt"

	pb "bnk.to/core/api/v1/loans"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

func (s *Server) UndoWriteOff(ctx context.Context, req *pb.UndoWriteOffRequest) (*emptypb.Empty, error) {
	if err := s.Auth.CheckPerm(ctx, req, "v1.accounts.loans.undowriteoff"); err != nil {
		return nil, err
	}

	return nil, fmt.Errorf("unimplemented")
}
