// Code generated by gen.go. DO NOT EDIT.
// To avoid your changes from being overwritten, delete this header.

package loans

import (
	"context"

	pb "bnk.to/core/api/v1/loans"
	"bnk.to/core/tools/db"
	"bnk.to/core/tools/db/mux"
)

func (s *Server) UpdateFunding(ctx context.Context, req *pb.UpdateFundingRequest) (*pb.InvestorFund, error) {
	if err := s.Auth.CheckPerm(ctx, req, "v1.accounts.loans.fundings.update"); err != nil {
		return nil, err
	}

	storage := mux.Storage(ctx)
	v, err := db.NewLoanInvestorFund(req.Body)
	if err != nil {
		return nil, err
	}
	if err := storage.UpdateLoanInvestorFundByFundID(ctx, &v); err != nil {
		return nil, err
	}
	return req.Body, nil
}
