package gw

// Code generated by gen.go. DO NOT EDIT.

import (
	"context"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"google.golang.org/grpc"

	backupspb "bnk.to/core/api/v1/backups"
	branchespb "bnk.to/core/api/v1/branches"
	bulkspb "bnk.to/core/api/v1/bulks"
	cardspb "bnk.to/core/api/v1/cards"
	centrespb "bnk.to/core/api/v1/centres"
	clientspb "bnk.to/core/api/v1/clients"
	commentspb "bnk.to/core/api/v1/comments"
	consumerspb "bnk.to/core/api/v1/consumers"
	currenciespb "bnk.to/core/api/v1/currencies"
	depositspb "bnk.to/core/api/v1/deposits"
	documentspb "bnk.to/core/api/v1/documents"
	fieldspb "bnk.to/core/api/v1/fields"
	groupspb "bnk.to/core/api/v1/groups"
	importspb "bnk.to/core/api/v1/imports"
	jobspb "bnk.to/core/api/v1/jobs"
	ledgerspb "bnk.to/core/api/v1/ledgers"
	loanspb "bnk.to/core/api/v1/loans"
	notificationspb "bnk.to/core/api/v1/notifications"
	orgpb "bnk.to/core/api/v1/org"
	productspb "bnk.to/core/api/v1/products"
	ratespb "bnk.to/core/api/v1/rates"
	reportspb "bnk.to/core/api/v1/reports"
	revolvingpb "bnk.to/core/api/v1/revolving"
	rolespb "bnk.to/core/api/v1/roles"
	taskspb "bnk.to/core/api/v1/tasks"
	transactionspb "bnk.to/core/api/v1/transactions"
	userspb "bnk.to/core/api/v1/users"
	utilpb "bnk.to/core/api/v1/util"
)

// Services are service endpoint handlers.
var Services = []func(context.Context, *runtime.ServeMux, string, []grpc.DialOption) error{
	orgpb.RegisterAccountingServiceHandlerFromEndpoint,
	ledgerspb.RegisterAccountsServiceHandlerFromEndpoint,
	revolvingpb.RegisterAccountsServiceHandlerFromEndpoint,
	backupspb.RegisterBackupServiceHandlerFromEndpoint,
	branchespb.RegisterBranchesServiceHandlerFromEndpoint,
	bulkspb.RegisterBulksServiceHandlerFromEndpoint,
	cardspb.RegisterCardsServiceHandlerFromEndpoint,
	centrespb.RegisterCentresServiceHandlerFromEndpoint,
	orgpb.RegisterChannelsServiceHandlerFromEndpoint,
	rolespb.RegisterClientRoleServiceHandlerFromEndpoint,
	clientspb.RegisterClientsServiceHandlerFromEndpoint,
	commentspb.RegisterCommentsServiceHandlerFromEndpoint,
	consumerspb.RegisterConsumersServiceHandlerFromEndpoint,
	currenciespb.RegisterCurrencyServiceHandlerFromEndpoint,
	productspb.RegisterDepositProductsServiceHandlerFromEndpoint,
	transactionspb.RegisterDepositTransactionsServiceHandlerFromEndpoint,
	depositspb.RegisterDepositsServiceHandlerFromEndpoint,
	documentspb.RegisterDocumentsServiceHandlerFromEndpoint,
	ledgerspb.RegisterEntriesServiceHandlerFromEndpoint,
	fieldspb.RegisterFieldsServiceHandlerFromEndpoint,
	groupspb.RegisterGroupsServiceHandlerFromEndpoint,
	cardspb.RegisterHoldConfigServiceHandlerFromEndpoint,
	orgpb.RegisterHolidaysServiceHandlerFromEndpoint,
	importspb.RegisterImportsServiceHandlerFromEndpoint,
	jobspb.RegisterJobsServiceHandlerFromEndpoint,
	productspb.RegisterLoanProductsServiceHandlerFromEndpoint,
	transactionspb.RegisterLoanTransactionsServiceHandlerFromEndpoint,
	loanspb.RegisterLoansServiceHandlerFromEndpoint,
	notificationspb.RegisterNotificationsServiceHandlerFromEndpoint,
	orgpb.RegisterOrganizationServiceHandlerFromEndpoint,
	currenciespb.RegisterRatesServiceHandlerFromEndpoint,
	ratespb.RegisterRatesServiceHandlerFromEndpoint,
	reportspb.RegisterReportsServiceHandlerFromEndpoint,
	productspb.RegisterRiskLevelsServiceHandlerFromEndpoint,
	orgpb.RegisterSetupServiceHandlerFromEndpoint,
	taskspb.RegisterTasksServiceHandlerFromEndpoint,
	rolespb.RegisterUserRolesServiceHandlerFromEndpoint,
	userspb.RegisterUsersServiceHandlerFromEndpoint,
	utilpb.RegisterUtilServiceHandlerFromEndpoint,
}
