// Package db contains generated code from xo.
package db

// Code generated by xo. DO NOT EDIT.

import (
	"context"
	"time"

	timestamppb "google.golang.org/protobuf/types/known/timestamppb"

	"bnk.to/core/api/v1/rates"
)

// RateIndexRate represents a row from 'rate_index_rates'.
type RateIndexRate struct {
	ID        int32     `json:"id"`         // id
	RateID    string    `json:"rate_id"`    // rate_id
	SourceID  string    `json:"source_id"`  // source_id
	UserID    string    `json:"user_id"`    // user_id
	Rate      float64   `json:"rate"`       // rate
	Notes     string    `json:"notes"`      // notes
	StartTime time.Time `json:"start_time"` // start_time
	// xo fields
	Exists, Deleted bool
}

func NewRateIndexRate(pb *rates.IndexRate) (RateIndexRate, error) {
	if pb == nil {
		return RateIndexRate{}, ErrNilType{"RateIndexRate"}
	}
	rir := RateIndexRate{
		RateID:    pb.RateID,
		SourceID:  pb.SourceID,
		UserID:    pb.UserID,
		Rate:      pb.Rate,
		Notes:     pb.Notes,
		StartTime: pb.StartTime.AsTime(),
	}
	return rir, nil
}

func (rir RateIndexRate) PB() (*rates.IndexRate, error) {
	pb := &rates.IndexRate{
		RateID:    rir.RateID,
		SourceID:  rir.SourceID,
		UserID:    rir.UserID,
		Rate:      rir.Rate,
		Notes:     rir.Notes,
		StartTime: timestamppb.New(rir.StartTime),
	}
	return pb, nil
}

type RateIndexRateRepository interface {
	InsertRateIndexRate(context.Context, *RateIndexRate) error
	ListRateIndexRates(context.Context, string, int32, string, *ListPosition) (ListStat, []*RateIndexRate, *ListPosition, error)

	// From rate_index_rates_pkey
	RateIndexRateByID(context.Context, int32) (*RateIndexRate, error)

	UpdateRateIndexRateByID(context.Context, *RateIndexRate) error
	DeleteRateIndexRateByID(context.Context, int32) error

	// From rate_index_rates_rate_id_idx
	RateIndexRateByRateID(context.Context, string) (*RateIndexRate, error)

	UpdateRateIndexRateByRateID(context.Context, *RateIndexRate) error
	DeleteRateIndexRateByRateID(context.Context, string) error
}
